name: Bug Report
description: Report any bugs here. We will be pleased to support you programming!
labels: ['template: bug']
body:
  - type: markdown
    attributes:
      value: |
        This template is to help you report bugs of VSC-Gameboy
        - If you have more questions personally, contact junman9595@gmail.com
  - type: dropdown
    id: service-type
    attributes:
      label: Which part does this bug appears?(or the part you guess)
      options:
        - Game
        - Platform
        - Environment
    validations:
      required: true
  - type: input
    attributes:
      label: Link to the code that reproduces this issue
      description: |
        A link to a **public** file of your repository
      placeholder: 'https://github.com/your/repository/path'
  - type: textarea
    attributes:
      label: To Reproduce
      description: A step-by-step description of how to reproduce the issue, based on the linked reproduction. Screenshots can be provided in the issue body below. If using code blocks, make sure that [syntax highlighting is correct](https://docs.github.com/en/get-started/writing-on-github/working-with-advanced-formatting/creating-and-highlighting-code-blocks#syntax-highlighting) and double check that the rendered preview is not broken.
      placeholder: |
        We highly recommend you to import image/gif/mp4 of issue state
        ![image](link of your image)
        1. Start the application in development
        2. If I do THIS
        3. THAT issue happens
    validations:
      required: true
  - type: textarea
    attributes:
      label: Current vs. Expected behavior
      description: A clear and concise description of what the bug is, and what you expected to happen.
      placeholder: |
        'Not Mandatory'
        'Following the steps from the previous section, I expected A to happen, but I observed B instead'
  - type: textarea
    attributes:
      label: Additional context
      description: |
        Any extra information that might help us investigate.
      placeholder: |
        'Not Mandatory'
        I am facing issue from space-invader game when I restart the game before finishing the game.
  - type: input
    attributes:
      label: Related Issues
      description: If this bug is related to any existing issues, please link them here. This helps us track and manage interconnected problems more effectively.
      placeholder: 'e.g., #2, #32'

